name: Lint Code

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install
    - name: Run Linter
      run: npx eslint .

  list-content:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: list repo content
      run: ls ${{ github.workspace }}

  echo-something:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: echo "hello pipeline"
      run: echo "hello pipeline"

  cat-file:
    runs-on: ubuntu-latest
    needs: list-content
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: cat file1
      run: cat ${{ github.worspace }}/file1.js
